#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking code formatting with Prettier..."
npx prettier --check "src/**/*.ts?(x)"

if [ $? -ne 0 ]; then
  echo "Code formatting errors found. Please fix them and try again."
  exit 1
fi

echo "Running TypeScript compiler..."
npx tsc

if [ $? -ne 0 ]; then
  echo "TypeScript errors found. Please fix them and try again."
  exit 1
fi

echo "All checks passed."
